export default function () {
  return { icons }
}

export const icons = [
  { text: '奖杯', icon: '󰀭' },
  { text: '挥手', icon: '󰀮' },
  { text: '四本', icon: '󰀩' },
  { text: '浆果丛', icon: '󰀠' },
  { text: '二本', icon: '󰀝' },
  { text: '牛角', icon: '󰀥' },
  { text: '盐', icon: '󰀨' },
  { text: '眼球草', icon: '󰀣' },
  { text: '营火', icon: '󰀤' },
  { text: '大拇指', icon: '󰀫' },
  { text: '白宝石', icon: '󰀧' },
  { text: '肉肉', icon: '󰀦' },
  { text: '背包', icon: '󰀞' },
  { text: '胡萝卜', icon: '󰀡' },
  { text: '虫洞', icon: '󰀯' },
  { text: '蜂巢', icon: '󰀟' },
  { text: '铲子', icon: '󰀪' },
  { text: '姐姐花', icon: '󰀜' },
  { text: '陷阱', icon: '󰀬' },
  { text: '煎蛋', icon: '󰀢' },
  { text: '肌肉', icon: '󰀙' },
  { text: '战斗', icon: '󰀘' },
  { text: '火把', icon: '󰀛' },
  { text: '金块', icon: '󰀚' },
  { text: '假牙', icon: '󰀆' },
  { text: '箱子', icon: '󰀂' },
  { text: '农场', icon: '󰀇' },
  { text: '切斯特', icon: '󰀃' },
  { text: '坟墓', icon: '󰀊' },
  { text: '幽灵', icon: '󰀉' },
  { text: '红心', icon: '󰀍' },
  { text: '火焰', icon: '󰀈' },
  { text: '火腿棒', icon: '󰀋' },
  { text: '灯泡', icon: '󰀏' },
  { text: '锅', icon: '󰀄' },
  { text: '牛牛', icon: '󰀁' },
  { text: '眼球', icon: '󰀅' },
  { text: '猪头', icon: '󰀐' },
  { text: '脑子', icon: '󰀓' },
  { text: '礼帽', icon: '󰀖' },
  { text: '一本', icon: '󰀔' },
  { text: '便便', icon: '󰀑' },
  { text: '红钻石', icon: '󰀒' },
  { text: '蜘蛛网', icon: '󰀗' },
  { text: '锤子', icon: '󰀌' },
  { text: '胃', icon: '󰀎' },
  { text: '白骷髅', icon: '󰀕' },
  { text: '红骷髅', icon: '󰀀' }
]
